config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :categories, only: :show
  resources :articles, only: :show
end

app/models/article.rb
class Article < ActiveRecord::Base
  include TwitterClient

  belongs_to :category
  has_many :tweets, class_name: ArticleTweet

  validates :category_id, presence: true
  validates :url, uniqueness: { scope: :category_id }

  scope :recent, -> { order('created_at DESC') }

  def self.refresh_tweets!
    Article.recent.limit(150).each(&:load_tweets!)
  end

  def load_tweets!
    results = twitter_client.search(self.url, count: 100, result_type: 'recent')
    results.each do |status|
      ArticleTweet.create(article: self, tweet_id: status.id, user_id: status.user.id, posted_at: status.created_at)
    end

    self.touch
  end

  def related_articles(num)
    user_ids = self.tweets.pluck(:user_id)
    article_stats = ArticleTweet.where.not(article: self).where(user_id: user_ids)
      .group(:article_id).order('count_user_id desc').count('user_id')

    articles = Article.recent.where(id: article_stats.keys.first(num))

    if articles.size < num
      articles + category_related_articles(num - articles.size)
    else
      articles
    end
  end

  def category_related_articles(num)
    Article.recent.where.not(id: self.id).where(category: self.category).limit(num)
  end
end

app/models/article_tweet.rb
class ArticleTweet < ActiveRecord::Base
  belongs_to :article

  validates :tweet_id, presence: true, uniqueness: true
  validates :article_id, presence: true, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
  validates :posted_at, presence: true
end

app/models/category.rb
require 'rss'

class Category < ActiveRecord::Base
  has_many :articles

  def self.refresh_articles!
    Category.all.each(&:load_articles!)
  end

  def load_articles!
    rss = RSS::Parser.parse(open(self.rss_url))
    rss.items.each do |item|
      next if Article.where(url: item.link).exists?
      ogp = OpenGraph.new(item.link)
      Article.create(category: self, title: item.title, description: ogp.description, url: item.link, thumbnail_url: ogp.images.first, created_at: item.pubDate)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: :show

  def show
  end

  private

  def set_article
    @article = Article.find_by(id: params[:id])
    redirect_to root_path if @article.blank?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def index
    @categories = Category.all
  end

  def show
    @articles = @category.articles.recent.limit(30)
  end

  private

  def set_category
    @category = Category.find_by(id: params[:id])
    redirect_to root_path if @category.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    if content_for?(:title)
      "#{content_for(:title)} - #{t('title')}"
    else
      t('title')
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/show.html.haml
- content_for(:title) { @article.title }

- if @article.thumbnail_url.present?
  .featured_article
    .category= @article.category.name
    .thumbnail= image_tag @article.thumbnail_url
    .title= @article.title
- else
  .article
    .title= @article.title

.summary= "#{@article.description}…"

.lead_button
  = link_to 'このニュースを読む', @article.url

%h2
  %i.fa.fa-search
  関連するニュース
- cache @article, expires_in: 10.minutes do
  - @article.related_articles(3).each do |article|
    = link_to article_path(article) do
      .article
        .link= article.title

app/views/categories/index.html.haml
- @categories.each do |category|
  %h2.category_name= link_to category.name, category_path(category)
  - category.articles.recent.first(5).each_with_index do |article, index|
    - if index == 0 && article.thumbnail_url.present?
      = link_to article_path(article) do
        .featured_article
          .thumbnail= image_tag article.thumbnail_url
          .title= article.title
    - else
      = link_to article_path(article) do
        .article
          .title= article.title

app/views/categories/show.html.haml
- content_for(:title) { "#{@category.name}のニュース一覧" }

%h2.category_name= "#{@category.name}のニュース一覧"
- @articles.each_with_index do |article, index|
  - if index % 5 == 0 && article.thumbnail_url.present?
    = link_to article_path(article) do
      .featured_article
        .thumbnail= image_tag article.thumbnail_url
        .title= article.title
  - else
    = link_to article_path(article) do
      .article
        .title= article.title

app/views/layouts/application.html.haml
!!!
%html{ lang: 'ja' }
  %head
    %meta{ charset: 'utf-8' }
    %title= title
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' }
  %body
    %h1.title
      = link_to root_path do
        %i.fa.fa-newspaper-o
        = t('title')
    = yield
    .powered_by= t('powered_by')

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-42393162-9', 'auto');
      ga('send', 'pageview');